<?php

namespace App\Services;

use App\Jobs\SendNotificationJob;
use App\Models\AuditLog;
use App\Models\Notification;
use Carbon\Carbon;
use Illuminate\Support\Facades\Log;

class NotificationService
{
    /**
     * Dispatch a deterministic notification.
     * Enforces rate limiting/deduping based on identical payload within 24 hours.
     */
    public function send(int $userId, string $type, ?string $entityType, ?int $entityId, string $message, string $severity = 'LOW')
    {
        // Deduping / Rate Limiting (Prevent spam)
        // Check if an identical notification was sent to this user in the last 24 hours.
        $recentDuplicate = Notification::where('user_id', $userId)
            ->where('type', $type)
            ->where('entity_type', $entityType)
            ->where('entity_id', $entityId)
            ->where('created_at', '>=', Carbon::now()->subHours(24))
            ->exists();

        if ($recentDuplicate) {
            Log::info("Notification Skipped (Rate Limited): Type {$type} for User {$userId}.");

            return null; // Return cleanly without dispatching
        }

        // Persist Notification
        /** @var \App\Models\Notification $notification */
        $notification = Notification::create([
            'user_id' => $userId,
            'type' => $type,
            'entity_type' => $entityType,
            'entity_id' => $entityId,
            'message' => $message,
            'severity' => $severity,
        ]);

        // Audit Trail Integration
        AuditLog::create([
            'user_id' => \Illuminate\Support\Facades\Auth::id() ?? 1, // Fallback to system admin if generated by Cron
            'entity_type' => $entityType ?? 'SYSTEM',
            'entity_id' => $entityId ?? 0,
            'action_type' => 'NOTIFICATION_CREATED',
            'old_values' => json_encode([]),
            'new_values' => json_encode([
                'notification_id' => $notification->id,
                'target_user_id' => $userId,
                'type' => $type,
                'severity' => $severity,
            ]),
            'ip_address' => request()->ip() ?? '127.0.0.1',
            'user_agent' => request()->userAgent() ?? 'SYSTEM_CRON',
        ]);

        // Asynchronous Delivery for High/Critical severities
        if (in_array($severity, ['HIGH', 'CRITICAL'])) {
            SendNotificationJob::dispatch($notification->id)->onQueue('high-priority');
        } else {
            // General background queue
            SendNotificationJob::dispatch($notification->id)->onQueue('default');
        }

        return $notification;
    }

    /**
     * Get unread notifications for a user
     */
    public function getUnreadCount(int $userId): int
    {
        return Notification::where('user_id', $userId)->where('is_read', false)->count();
    }

    /**
     * Mark a specific notification or all notifications as read
     */
    public function markAsRead(int $userId, ?int $notificationId = null)
    {
        $query = Notification::where('user_id', $userId)->where('is_read', false);

        if ($notificationId) {
            $query->where('id', $notificationId);
        }

        return $query->update([
            'is_read' => true,
            'read_at' => Carbon::now(),
        ]);
    }
}
