<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>NAMA File Tracking - Secure Report</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            font-size: 10pt;
            color: #333;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #003B73;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            color: #003B73;
            font-size: 18pt;
        }

        .meta {
            font-size: 8pt;
            color: #666;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            padding: 10px;
            background: #f9f9f9;
        }

        .meta p {
            margin: 2px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
            font-size: 9pt;
        }

        td {
            font-size: 8pt;
        }

        .footer {
            text-align: center;
            font-size: 7pt;
            color: #999;
            margin-top: 50px;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
    </style>
</head>

<body>

    <div class="header">
        <h1>NAMA NG - File Tracking System</h1>
        <h3>Operational Intelligence Report</h3>
    </div>

    <div class="meta">
        <strong>Forensic Provenance Details:</strong>
        <p><strong>Generated At:</strong> {{ $watermarkInfo['timestamp'] }}</p>
        <p><strong>Generated By:</strong> {{ $watermarkInfo['user_name'] }} (ID: {{ $watermarkInfo['user_id'] }})</p>
        <p><strong>Filters Applied:</strong> {{ $watermarkInfo['filters'] }}</p>
        <p><strong>Integrity Checksum (SHA256):</strong> {{ $watermarkInfo['integrity_hash'] }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>File Reference</th>
                <th>Title</th>
                <th>Current Owner</th>
                <th>Department</th>
                <th>Status</th>
                <th>Priority</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($files as $file)
                <tr>
                    <td>{{ $file->file_reference_number }}</td>
                    <td>{{ $file->title }}</td>
                    <td>{{ $file->currentOwner->name ?? 'N/A' }}</td>
                    <td>{{ $file->currentDepartment->name ?? 'N/A' }}</td>
                    <td>{{ $file->status->name ?? 'N/A' }}</td>
                    <td>{{ $file->priority_level }}</td>
                    <td>{{ $file->created_at->format('Y-m-d H:i') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This document is a certified extract from the Nigerian Airspace Management Agency File Tracking Ledger.</p>
        <p>Modification of this cryptographic export strictly violates the Official Secrets Act.</p>
    </div>

</body>

</html>
