name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: ntfs_testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql, dom, filter, gd, iconv, json, pcntl
        coverage: none

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Install NPM Dependencies & Build
      run: |
        npm install
        npm run build

    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Execute PHPUnit Suite
      run: php artisan test --parallel
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ':memory:'
